// API ENDPOINTS
const API_URL = 'https://api.fitm.online:1999'
// const API_URL = 'http://localhost:1999'

const SIGNUP_ENDPOINT = API_URL + '/signup'
const LOGIN_ENDPOINT = API_URL + '/login'
const SEND_PASSWORD_RESET_EMAIL_ENDPOINT =
	API_URL + '/email-password-reset-link'
const RESET_PASSWORD_ENDPOINT = API_URL + '/reset-password'

const LINKS_ENDPOINT = API_URL + '/links'
const LINK_PREVIEW_IMG_ENDPOINT = API_URL + '/pic/preview'
const CATS_ENDPOINT = API_URL + '/cats'
const CONTRIBUTORS_ENDPOINT = API_URL + '/contributors'
const SUMMARIES_ENDPOINT = API_URL + '/summaries'
const TAGS_ENDPOINT = API_URL + '/tags'
const CLICKS_ENDPOINT = API_URL + '/click'
const TOTALS_ENDPOINT = API_URL + '/totals'

const TMAP_ENDPOINT = API_URL + '/map'
const TMAP_PFP_ENDPOINT = API_URL + '/pic/profile'
const TMAP_ABOUT_ENDPOINT = API_URL + '/about'
const TMAP_EMAIL_ENDPOINT = API_URL + '/email'

// LIMITS
const LINKS_PAGE_LIMIT = 20
const MAX_CATS_PER_TAG = 15
const CATS_PAGE_LIMIT = 50

export {
	API_URL,
	CATS_ENDPOINT,
	CATS_PAGE_LIMIT,
	CLICKS_ENDPOINT,
	CONTRIBUTORS_ENDPOINT,
	LINK_PREVIEW_IMG_ENDPOINT,
	LINKS_ENDPOINT,
	LINKS_PAGE_LIMIT,
	LOGIN_ENDPOINT,
	MAX_CATS_PER_TAG,
	RESET_PASSWORD_ENDPOINT,
	SEND_PASSWORD_RESET_EMAIL_ENDPOINT,
	SIGNUP_ENDPOINT,
	SUMMARIES_ENDPOINT,
	TAGS_ENDPOINT,
	TMAP_ABOUT_ENDPOINT,
	TMAP_EMAIL_ENDPOINT,
	TMAP_ENDPOINT,
	TMAP_PFP_ENDPOINT,
	TOTALS_ENDPOINT,
}
